### ISSUE TITLE
What was it like to learn Fortran?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fortran#45]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Fortran? What was helpful while learning Fortran? What did you struggle with? How did you tackle problems?
1. In what ways did Fortran differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Fortran :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by pclausen** [comment]
> Learning Fortran 

I think that very few people since the 1990’s have learned Fortran because they felt curious or fascinated by this very old language. Instead, Fortran is a very common tool to solve numerical problems. Many robust and tested solutions are written in Fortran and many are still in production today and in many years to come.
I think there are two ways to Fortran; the scientific or as a software developer.
Many scientific communities have been using Fortran for many decades for solving numerical problems. Therefore, people as myself with a scientific or engineering background, typically learn Fortran in masters or PhD programs. Another way to Fortran is to be hired in an organization (like mine, Dassault Systèmes www.3ds.com) where many numerical algorithms are in Fortran and they continue to be developed in Fortran.

> How was your experience learning Fortran? 

I learned a bit of Fortran during my mechanical engineering studies as part of a finite element course where the main part of the program was prepared in Fortran and our assignment was to add critical parts, eg. the finite element formulation. But mainly as I started working full time on structural optimization full time in 2005.

> What was helpful while learning Fortran? 

Fortran was one of my first software languages after learning Basic and Pascal in my youth and Matlab in my studies. Fortran (FORmula TRANslator) is really good for writing numerical routines and not having object orientation kind of helped me, because I feel object oriented programs confuses me (any many other non-software folks, e.g scientists) more in the beginning than they helped.

> What did you struggle with?

Anything else than numerics is a pain in Fortran. File io, graphics, structuring code is often much better in almost any other languages. Therefore, many codes have C/C++ or Python wrappers around Fortran to avoid parts of this pain.

> How did you tackle problems?

I did not tackle these problems - other people in my organisation mainly did.

> In what ways did Fortran differ from other languages you knew at the time? 

Fortran is procedural like Pascal and Basic so that part felt easy at the time. Fortran is fairly easy to learn, because it is fairly limited and most Fortran programmers are generally conservative and not using too many new language features, even though Fortran has developed over the 60 years it has been in use.

> What was hard to learn? 

The Fortran90 modules takes some getting used to. Also very old Fortran77 code can be difficult to read and will have memory saving constructs like `equivalence`, implicit variables and too many `goto`’s. If the code is still being actively maintained and modified I think removing these constructs is often worth the hassle but it is a risk and YMMW.

> What did you have to unlearn? 

Nothing really. One index may be an issue of you come from Java, C/C++ or python.

> What syntax did you have to remap? 

Fortran syntax is fairly limited compared to other languages 

> What concepts carried over nicely?

The best thing in Fortran90 is array operations, an essential component of numerics. 
`A(:,:) = B(:,:) + C(:,:)`
Which is similar in Python and Matlab.

**Comment by hiljusti** [comment]
> Learning Fortran

For what it's worth, I learned Fortran out of curiosity. I haven't met anyone else that has done that, though. I'll second that the big developer community I've seen is related to scientific computing. I've also seen some applications in data science where Fortran is a better choice than C when implementing something low level.

> What did you have to unlearn

Variables being scoped to a call stack instance of a function. (i.e. general recursion)

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
